### ISSUE TITLE
Clear error message on non WebGL2-enabled browsers

### ISSUE THREAD

**Issue by ericvrp** [iotaledger/curl.lib.js#12]
Could this package please provide a nice error message when used on non WebGL2-enabled browsers. I was rather naively trying to use it on a 2011 notebook and saw this error in Google Chrome's developers console until I started to realize what was going on.

> curl.min.js:1 Uncaught TypeError: Cannot read property 'MAX_TEXTURE_SIZE' of null
>     at Object.<anonymous> (curl.min.js:1)
>     at n (curl.min.js:1)
>     at Object.<anonymous> (curl.min.js:1)
>     at n (curl.min.js:1)
>     at Object.<anonymous> (curl.min.js:1)
>     at n (curl.min.js:1)
>     at Object.<anonymous> (curl.min.js:1)
>     at n (curl.min.js:1)
>     at curl.min.js:1

**Comment by paulhandy** [comment]
This error should be resolved in commit 1e72b99
