### ISSUE TITLE
Hello, I am trying to create the dist folder to use it in the browser

### ISSUE THREAD

**Issue by bioduds** [iotaledger/curl.lib.js#2]
Hello, I am trying to create the dist folder to use it in the browser. I'm getting this:

Can you please help me? 

![screenshot_20170702_182843](https://user-images.githubusercontent.com/2072730/27773694-e691f4fe-5f55-11e7-8cfd-5d76e7201ca1.png)

**Comment by pRizz** [comment]
Update `node` and `npm`
