### ISSUE TITLE
curl init() breaks when running it on nodejs

### ISSUE THREAD

**Issue by brunoamancio** [iotaledger/curl.lib.js#20]
This issue happens when running code on a nodeJS app.

After requiring the lib and invoking init() the code breaks in pearldiver.js.
const search = (**instance**, states, minWeight)

Instance is undefined.

**Comment by paulhandy** [comment]
This is a webgl library, so it doesn't run in node.js

**Comment by brunoamancio** [comment]
still, the pow algorithm should be executed, even if its isn't so efficient. Or is it not supposed to?

**Comment by brunoamancio** [comment]
Just forget about it.. I've found ccurl.
